apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openldap-phpldapadmin.fullname" . }}-openldap-config
  labels:
    {{- include "openldap-phpldapadmin.labels" . | nindent 4 }}
data:
  01-overlay.ldif: |
    dn: olcOverlay=ppolicy,olcDatabase={1}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcPPolicyConfig
    olcOverlay: ppolicy
    olcPPolicyDefault: cn=default,ou=policies,{{ include "openldap-phpldapadmin.baseDn" . }}
    olcPPolicyHashCleartext: TRUE
