apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap-phpldapadmin.fullname" . }}-openldap-secrets
  labels:
    {{- include "openldap-phpldapadmin.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: {{ .Values.openldap.adminPassword | b64enc | quote }}
  LDAP_CONFIG_PASSWORD: {{ .Values.openldap.configPassword | b64enc | quote }}
