apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openldap-phpldapadmin.fullname" . }}-phpldapadmin
  labels:
    {{- include "openldap-phpldapadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openldap-phpldapadmin.selectorLabels" . | nindent 6 }}
      component: phpldapadmin
  template:
    metadata:
      labels:
        {{- include "openldap-phpldapadmin.selectorLabels" . | nindent 8 }}
        component: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: "{{ .Values.phpldapadmin.image.repository }}:{{ .Values.phpldapadmin.image.tag }}"
        imagePullPolicy: {{ .Values.phpldapadmin.image.pullPolicy }}
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: "{{ .Values.phpldapadmin.config.server_host }}"
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        ports:
        - containerPort: 80
          name: http
        resources:
          {{- toYaml .Values.phpldapadmin.resources | nindent 10 }}
