apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap-phpldapadmin.fullname" . }}-phpldapadmin
  labels:
    {{- include "openldap-phpldapadmin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.phpldapadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openldap-phpldapadmin.selectorLabels" . | nindent 4 }}
    component: phpldapadmin
